server:
  port: 8040 #${SERVER_PORT:8040}

spring:
  application:
    name: department-service
  task:
    scheduling:
      enabled: true
      pool:
        size: 2

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5434/department_db}
    username: ${SPRING_DATASOURCE_USERNAME:department_user}
    password: ${SPRING_DATASOURCE_PASSWORD:department_pass}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/employee-realm}
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://localhost:8080/realms/employee-realm/protocol/openid-connect/certs}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true


logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{correlationId}] [%X{username}] %logger{36} - %msg%n"
  file:
    name: /app/logs/department-service.log
  level:
    root: INFO
    com.emplmanagement: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true

info:
  app:
    name: Department Service
    description: Department Management Microservice
    version: 1.0.0
