server:
  port: 8041 #${SERVER_PORT:8041}

spring:
  application:
    name: employee-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/employee_db}
    username: ${SPRING_DATASOURCE_USERNAME:employee_user}
    password: ${SPRING_DATASOURCE_PASSWORD:employee_pass}

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/employee-realm}
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://localhost:8080/realms/employee-realm/protocol/openid-connect/certs}

  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true